export const topicUserData = [
  {
    id: 1,
    name: 'Topic Name',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    student: 'Tran Van Ben',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    name: 'Topic Name',
    topicId: '002',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    student: 'Tran Van Ben',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 3,
    name: 'Topic Name',
    topicId: '003',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    student: 'Tran Van Ben',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 4,
    name: 'Topic Name',
    topicId: '004',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    student: 'Tran Van Ben',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
];
