export const topicList = [
  {
    id: 1,
    name: 'value.adornedStart',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      ' Indicate whether the child Input or Select component has a start adornment.',
    link: '(bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    name: 'value.setAdornedStart',
    topicId: '002',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: ' Setter function for adornedStart state value.',
    link: '(func)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 3,
    name: 'value.color',
    topicId: '003',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      ' The theme color is being used, inherited from FormControl color prop .',
    link: ' (string)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 4,
    name: 'Indicate whether the component is being displayed in a disabled state, inherited from FormControl disabled prop.',
    topicId: '004',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      ' Indicate whether the component is being displayed in a disabled state, inherited from FormControl disabled prop.',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 5,
    name: 'value.error',
    topicId: '005',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 6,
    name: 'value.error',
    topicId: '006',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 7,
    name: 'value.error',
    topicId: '007',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 8,
    name: 'value.error',
    topicId: '008',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 9,
    name: 'value.error',
    topicId: '009',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 10,
    name: 'value.error',
    topicId: '010',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 11,
    name: 'value.error',
    topicId: '011',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 12,
    name: 'value.error',
    topicId: '012',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description:
      '  Indicate whether the component is being displayed in an error state, inherited from FormControl error prop',
    link: ' (bool)',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
];
