export const topicList = [
  {
    id: 1,
    name: 'Topic Name',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 3,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 4,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 5,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 1,
    name: 'Topic Name',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 3,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 4,
    topicId: '001',
    name: 'Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 5,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 1,
    name: 'Topic Name',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 3,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 4,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 5,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 1,
    name: 'Topic Name   ',
    topicId: '001',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    teacher: 'Nguyen Van An',
    major: 'CNTT',
  },
  {
    id: 2,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    major: 'CNTT',
  },
  {
    id: 3,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    major: 'CNTT',
  },
  {
    id: 4,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    major: 'CNTT',
  },
  {
    id: 5,
    topicId: '001',
    name: 'Topic Name',
    startDate: '12/12/2012',
    endDate: '12/12/2012',
    description: 'description',
    link: 'link',
    status: 'Active',
    major: 'CNTT',
  },
];
